spring:
  application:
    name: aws-image-uploader
  servlet:
    multipart:
      max-file-size: 50MB

  datasource:
    url: jdbc:postgresql://localhost:5432/awsimageuploaderdb
    username: awsuploader
    password: development

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true

server:
  port: 8080

